//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Utils
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class COMPULASTEntities1 : DbContext
    {
        public COMPULASTEntities1()
            : base("name=COMPULASTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_LISTAPEDIDOS_Result> SP_LISTAPEDIDOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAPEDIDOS_Result>("SP_LISTAPEDIDOS");
        }
    
        public virtual ObjectResult<SP_LISTAPEDIDOSxFECHAS_Result> SP_LISTAPEDIDOSxFECHAS(Nullable<System.DateTime> f1, Nullable<System.DateTime> f2)
        {
            var f1Parameter = f1.HasValue ?
                new ObjectParameter("F1", f1) :
                new ObjectParameter("F1", typeof(System.DateTime));
    
            var f2Parameter = f2.HasValue ?
                new ObjectParameter("F2", f2) :
                new ObjectParameter("F2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAPEDIDOSxFECHAS_Result>("SP_LISTAPEDIDOSxFECHAS", f1Parameter, f2Parameter);
        }
    }
}
