USE MASTER
GO

IF DB_ID('COMPULAST') IS NOT NULL 
	DROP DATABASE COMPULAST
GO

CREATE DATABASE COMPULAST
GO

USE COMPULAST
GO

CREATE TABLE [dbo].[TBUSUARIO](
	[USUARI_CODIGO] [varchar](8) NOT NULL,
	[USUARI_PASS] [varchar](10) NULL,
	[USUARI_FECPASS] [varchar](8) NULL,
	[USUARI_ESTADO] [varchar](1) NULL,
	[USUARI_ESTASOCIADO] [varchar](2) NULL,
	[USUARI_NIVEL] [varchar](2) NULL,
	[USUARI_FECINI] [varchar](8) NULL,
	[USUARI_FECFIN] [varchar](8) NULL,
	[USUARI_DIAHORACC] [varchar](168) NULL,
	[USUARI_ACCFER] [varchar](1) NULL,
	[USUARI_NUMPASS] [varchar](1) NULL,
	[USUARI_PASSANT] [varchar](40) NULL,
	[USUARI_SYS_CRE] [varchar](20) NULL,
	[USUARI_SYS_MOD] [varchar](20) NULL,
	[USUARI_SYS_EST] [varchar](1) NULL,
	[USUARI_APEPAT] [varchar](15) NULL,
	[USUARI_APEMAT] [varchar](15) NULL,
	[USUARI_NOMBRES] [varchar](20) NULL,
	[USUARI_DOCIDENAC] [varchar](10) NULL,
	[USUARI_TIPDOCIDE] [varchar](1) NULL,
	[USUARI_CODDOCIDE] [varchar](10) NULL,
	[USUARI_TIPO] [varchar](2) NULL,
	[USUARI_TIPO_EXP] [varchar](2) NULL,
	[USUARI_DIAS_EXP] [varchar](4) NULL,
	[USUARI_CORREO] [varchar](50) NULL,
	[PERSON_COD_INTERNO] [varchar](10) NULL,
	[USUARI_TELEFONO] [varchar](50) NULL,
	[USUARI_SEXO] [varchar](2) NULL,
	[USUARI_FECHANAC] [varchar](8) NULL,
	[USUARI_DIRECCION] [varchar](250) NULL,
	[USUARI_PAIS] [varchar](6) NULL,
	[USUARI_DPTO] [varchar](6) NULL,
	[USUARI_PROV] [varchar](6) NULL,
	[USUARI_DIST] [varchar](6) NULL,
	[USUARI_EMPRESA] [varchar](250) NULL,
	[USUARI_EMPRESA_OFICINA] [varchar](250) NULL,
	[USUARI_EMPRESA_PUESTO] [varchar](250) NULL,
	[USUARI_PROVEEDOR] [varchar](1) NULL
) ON [PRIMARY]

ALTER TABLE TBUSUARIO ADD CONSTRAINT PK_TBUSUARIO PRIMARY KEY([USUARI_CODIGO])
GO

INSERT INTO TBUSUARIO (USUARI_CODIGO, USUARI_PASS, USUARI_APEPAT, USUARI_APEMAT, USUARI_NOMBRES, USUARI_CORREO, USUARI_TELEFONO) 
VALUES (1001, 'giomar', 'Limo', 'Caldas', 'Giomar', 'giomar@hotmail.com', 333333333);
INSERT INTO TBUSUARIO (USUARI_CODIGO, USUARI_PASS, USUARI_APEPAT, USUARI_APEMAT, USUARI_NOMBRES, USUARI_CORREO, USUARI_TELEFONO) 
VALUES (1002, 'valeria', 'Gabancho', 'Davila', 'Valeria', 'valeria@hotmail.com', 333333334);
INSERT INTO TBUSUARIO (USUARI_CODIGO, USUARI_PASS, USUARI_APEPAT, USUARI_APEMAT, USUARI_NOMBRES, USUARI_CORREO, USUARI_TELEFONO) 
VALUES (1003, 'arturo', 'Chaparro', 'Quispe', 'Arturo', 'arturo@hotmail.com', 333333335);

CREATE TABLE TB_PROVEEDOR
(
IDE_PROV	INT		NOT NULL	IDENTITY(1,1),
NOM_PROV	VARCHAR(45),
DIR_PROV 	VARCHAR(60) 	NOT NULL,
PRIMARY KEY (IDE_PROV)
)
GO

INSERT INTO TB_PROVEEDOR VALUES
('SERCOPLUS', 'NULL'),
('IMPACTO', 'NULL'),
('C&C COMPUTER SERVICE S.A.C', 'NULL')
GO

CREATE TABLE TB_MARCA
(
ID_MARCA	INT		NOT NULL	IDENTITY(1,1),
NOM_MARCA	VARCHAR(45),
PRIMARY KEY (ID_MARCA)
)
GO

INSERT INTO TB_MARCA VALUES
('GIGABYTE'),
('ASUS'),
('MSI'),
('ASUS'),
('ASROCK'),
('COUGAR'),
('SAMSUNG'),
('HALION'),
('HYPERX'),
('SEAGATE'),
('LOGITECH'),
('ASUS'),
('AMD'),
('INTEL'),
('COOLER MASTER'),
('THERMALTAKE'),
('ANTRYX'),
('EVGA'),
('INNO3D')
GO

CREATE TABLE TB_PROCESADOR
(
ID_PROC		INT		NOT NULL	IDENTITY(1,1),
NOM_PROC	VARCHAR(45),
IDE_PROV	INT,
ID_MARCA	INT,
NUM_NUCL	INT,
NUM_HILO	INT,
REL_BASE	NUMERIC(2,1),
REL_MAXI	NUMERIC(2,1),
TDP_PROC	NUMERIC(4),
GPU_INTE	BIT,
PRE_PROC	DECIMAL(10,2),
PRIMARY KEY (ID_PROC),
FOREIGN KEY(IDE_PROV) REFERENCES TB_PROVEEDOR(IDE_PROV),
FOREIGN KEY(ID_MARCA) REFERENCES TB_MARCA(ID_MARCA)
)
GO

INSERT INTO TB_PROCESADOR VALUES
('AMD ATHLON 3000G', 1, 13, 2, 4, 3.50, 3.50, 35, 1, 232.96),
('AMD RYZEN 3 3200G', 1, 13, 4, 4, 3.60, 4.00, 65, 1, 451.36),
('AMD RYZEN 5 3400G', 1, 13, 4, 8, 3.70, 4.20, 65, 1, 720.72),
('AMD RYZEN 5 3600', 1, 13, 6, 12, 3.60, 4.20, 65, 0, 910.00),
('AMD RYZEN 7 3700X', 1, 13, 8, 16, 3.60, 4.40, 65, 0, 1477.84),
('AMD RYZEN 9 3900X', 1, 13, 12, 24, 3.80, 4.60, 105, 0, 2366.00),
('INTEL CORE I3 10100', 1, 14, 4, 8, 3.60, 4.30, 65, 1, 502.32),
('INTEL CORE I5 10400', 1, 14, 6, 12, 2.90, 4.30, 65, 1, 859.04),
('INTEL CORE I7 10700K', 1, 14, 8, 16, 3.80, 5.10, 125, 1, 1820.00),
('INTEL CORE I9 10900K', 1, 14, 10, 20, 3.70, 5.30, 125, 1, 2431.52)
GO

CREATE TABLE TB_GPU
(
IDE_GPU		INT			NOT NULL	IDENTITY(1,1),
DES_GPU		VARCHAR(45)	NOT NULL,
IDE_PROV	INT,
ID_MARCA	INT,
MEM_GPU		INT,
PRE_GPU		DECIMAL(10,2) NOT NULL,
STK_GPU		INT,
FOT_GPU		VARCHAR(50),
PRIMARY KEY (IDE_GPU),
FOREIGN KEY(IDE_PROV) REFERENCES TB_PROVEEDOR(IDE_PROV),
FOREIGN KEY(ID_MARCA) REFERENCES TB_MARCA(ID_MARCA)
)
GO

INSERT INTO TB_GPU VALUES
('VGA INNO3D NVIDIA GT 1030', 1, 19, 2, 371.28, 59, '~/fotos_gpu/1.jpg')
GO

CREATE TABLE TB_MOTHERBOARD
(
IDE_MB		INT		NOT NULL	IDENTITY(1,1),
DES_MB		VARCHAR(45),
IDE_PROV	INT,
ID_MARCA	INT,
PRIMARY KEY(IDE_MB),
FOREIGN KEY(IDE_PROV) REFERENCES TB_PROVEEDOR(IDE_PROV),
FOREIGN KEY(ID_MARCA) REFERENCES TB_MARCA(ID_MARCA)
)
GO

CREATE TABLE TB_RAM
(
ID_RAM		INT		NOT NULL	IDENTITY(1,1),
DES_RAM		VARCHAR(45),
IDE_PROV	INT,
ID_MARCA	INT,
MEM_RAM		INT,
FRE_RAM		INT,
PRIMARY KEY(ID_RAM),
FOREIGN KEY(IDE_PROV) REFERENCES TB_PROVEEDOR(IDE_PROV),
FOREIGN KEY(ID_MARCA) REFERENCES TB_MARCA(ID_MARCA)
)
GO

INSERT INTO TB_RAM VALUES
('MEM. RAM HYPERX FURY 8GB DDR4 3200 MHZ', 1, 9, 8, 3200)
GO

CREATE TABLE TB_ALMACENAMIENTO
(
ID_ALM		INT		NOT NULL	IDENTITY(1,1),
DES_ALM		VARCHAR(45),
IDE_PROV	INT,
ID_MARCA	INT,
CAN_ALM		INT,
PRIMARY KEY(ID_ALM),
FOREIGN KEY(IDE_PROV) REFERENCES TB_PROVEEDOR(IDE_PROV),
FOREIGN KEY(ID_MARCA) REFERENCES TB_MARCA(ID_MARCA)
)
GO

INSERT INTO TB_ALMACENAMIENTO VALUES
('SEAGATE BARRACUDA 1TB SATA 7200 RPM', 1, 10, 1)
GO

CREATE TABLE TB_FUENTE
(
ID_PSU		INT		NOT NULL	IDENTITY(1,1),
DES_PSU		VARCHAR(45),
IDE_PROV	INT,
ID_MARCA	INT,
CAN_WAT		INT,
PSU_CER		BIT,
PRE_PSU	DECIMAL(10,2),
PRIMARY KEY(ID_PSU),
FOREIGN KEY(IDE_PROV) REFERENCES TB_PROVEEDOR(IDE_PROV),
FOREIGN KEY(ID_MARCA) REFERENCES TB_MARCA(ID_MARCA)
)
GO

INSERT INTO TB_FUENTE VALUES
('COOLER MASTERWATT LITE 500W', 1, 15, 500, 0, 178.36),
('CM MWE 550W 80 PLUS BRONZE V2', 1, 15, 550, 1, 247.52),
('HALION GAMING GE-550', 1, 8, 550, 0, 96.46),
('CM MWE 650W 80 PLUS BRONZE V2', 1, 15, 650, 1, 291.20),
('CM MWE 750W 80 PLUS WHITE V2', 1, 15, 750, 1, 254.80),
('FUENTE ANTRYX B500W V2 2.3 BOX', 1, 17, 500, 0, 131.04),
('CM MWE 750W 80 PLUS BRONZE V2', 1, 15, 750, 1, 327.60),
('CM MWE GOLD 750 80 PLUS GOLD MODULAR', 1, 15, 750, 1, 444.08),
('THERMALTAKE LITEPOWER 550W', 1, 16, 550, 0, 145.60),
('EVGA SUPERNOVA 1300 G2, 80+ GOLD', 1, 18, 1300, 1, 1230.32)
GO

CREATE TABLE TB_PC
(
ID_PC		INT		NOT NULL	IDENTITY(1,1),
DES_PC		VARCHAR(15)	NOT NULL,
ID_PROC		INT,
ID_RAM		INT		NOT NULL,
ID_ALM		INT		NOT NULL,
ID_PSU		INT		NOT NULL,
PRE_PC	DECIMAL(10,2) NOT NULL,
STK_PC		INT,
FOT_PC		VARCHAR(50),
PRIMARY KEY (ID_PC),
FOREIGN KEY	(ID_PROC) REFERENCES TB_PROCESADOR(ID_PROC),
FOREIGN KEY	(ID_RAM) REFERENCES TB_RAM(ID_RAM),
FOREIGN KEY	(ID_ALM) REFERENCES TB_ALMACENAMIENTO(ID_ALM),
FOREIGN KEY	(ID_PSU) REFERENCES TB_FUENTE(ID_PSU),
)
GO

INSERT INTO TB_PC VALUES
('PC GAMER', 3, 1, 1, 1, 3200, 32, '~/fotos_pc/1.jpg')
GO

-------- SELECT
SELECT * FROM TB_PROVEEDOR
GO

SELECT * FROM TB_MARCA
GO

SELECT * FROM TB_PROCESADOR
GO

SELECT * FROM TB_GPU
GO

SELECT * FROM TB_RAM
GO

SELECT * FROM TB_ALMACENAMIENTO
GO

SELECT * FROM TB_FUENTE
GO

