USE COMPULAST
GO

--SP LISTADO DE PC
IF OBJECT_ID('SP_LISTADOxPC')IS NOT NULL 
	DROP PROC SP_LISTADOxPC
GO
CREATE PROC SP_LISTADOxPC
AS
SELECT P.ID_PC 'CODIGO',
	   P.DES_PC 'DESCRIPCION',
	   PR.NOM_PROC 'CPU',
	   R.DES_RAM 'RAM',
	   A.DES_ALM 'ALMACENAMIENTO',
	   F.DES_PSU 'FUENTE',
	   P.PRE_PC 'PRECIO',
	   P.STK_PC	'STOCK',
	   P.FOT_PC 'FOTO'

FROM TB_PC P JOIN TB_PROCESADOR PR ON
		PR.ID_PROC = P.ID_PROC JOIN TB_RAM R ON
		R.ID_RAM=P.ID_RAM JOIN TB_ALMACENAMIENTO A ON
		A.ID_ALM=P.ID_ALM JOIN TB_FUENTE F ON
		F.ID_PSU=P.ID_PSU
GO

EXECUTE SP_LISTADOxPC


-- procedimiento para validar acceso en el login

IF OBJECT_ID('SP_BUSCAR_USUARIO') IS NOT NULL 
	DROP PROC SP_BUSCAR_USUARIO
GO

CREATE OR ALTER PROCEDURE SP_BUSCAR_USUARIO
@p_usuari_codigo varchar(8),
@p_usuari_pass varchar(10)
AS
BEGIN
	SELECT USUARI_CODIGO, USUARI_PASS, USUARI_APEPAT, USUARI_APEMAT, USUARI_NOMBRES, USUARI_CORREO, USUARI_TELEFONO
	FROM [dbo].[TBUSUARIO]
	WHERE USUARI_CODIGO = @p_usuari_codigo and USUARI_PASS = @p_usuari_pass
END
GO

exec SP_BUSCAR_USUARIO 1001,'giomar'